mkdir disasm

mkdir disasm\code
mkdir disasm\code\common
mkdir disasm\code\common\menus
mkdir disasm\code\common\menus\church
mkdir disasm\code\common\menus\shop
mkdir disasm\code\common\scripting
mkdir disasm\code\common\scripting\text
mkdir disasm\code\common\stats
mkdir disasm\code\common\tech
mkdir disasm\code\common\tech\graphics
mkdir disasm\code\common\tech\interrupts
mkdir disasm\code\common\tech\sound
mkdir disasm\code\common\tech\sram
mkdir disasm\code\gameflow
mkdir disasm\code\gameflow\battle
mkdir disasm\code\gameflow\battle\battlescenes
mkdir disasm\code\gameflow\end
mkdir disasm\code\gameflow\headquarters
mkdir disasm\code\gameflow\special
mkdir disasm\code\gameflow\start
mkdir disasm\code\specialscreens
mkdir disasm\code\specialscreens\chapterscreen
mkdir disasm\code\specialscreens\readerscreen
mkdir disasm\code\specialscreens\segalogo
mkdir disasm\code\specialscreens\soundtest

mkdir disasm\data
mkdir disasm\data\battles
mkdir disasm\data\battles\global
mkdir disasm\data\battles\global\exits
mkdir disasm\data\graphics
mkdir disasm\data\graphics\battles
mkdir disasm\data\graphics\battles\backgrounds
mkdir disasm\data\graphics\battles\battlesprites
mkdir disasm\data\graphics\battles\battlesprites\allies
mkdir disasm\data\graphics\battles\battlesprites\allies\animations
mkdir disasm\data\graphics\battles\battlesprites\enemies
mkdir disasm\data\graphics\battles\battlesprites\enemies\animations
mkdir disasm\data\graphics\battles\platforms
mkdir disasm\data\graphics\battles\weapons
mkdir disasm\data\graphics\maps\maptilesets
mkdir disasm\data\graphics\mapsprites
mkdir disasm\data\graphics\portraits
mkdir disasm\data\graphics\specialscreens
mkdir disasm\data\graphics\specialscreens\chapterscreen
mkdir disasm\data\graphics\specialscreens\readerscreen
mkdir disasm\data\graphics\specialscreens\soundtest
mkdir disasm\data\graphics\tech
mkdir disasm\data\graphics\tech\windowlayouts
mkdir disasm\data\graphics\tech\windowlayouts\miscmessages
mkdir disasm\data\maps
mkdir disasm\data\maps\global
mkdir disasm\data\maps\spritesets
mkdir disasm\data\maps\tileanimations
mkdir disasm\data\scripting
mkdir disasm\data\scripting\ending
mkdir disasm\data\scripting\mapspritescripts
mkdir disasm\data\scripting\text
mkdir disasm\data\scripting\text\textbanks
mkdir disasm\data\stats
mkdir disasm\data\stats\allies
mkdir disasm\data\stats\classes
mkdir disasm\data\stats\enemies
mkdir disasm\data\stats\items
mkdir disasm\data\stats\ranges
mkdir disasm\data\stats\spells

mkdir disasm\layout